POST http://localhost:3001/api/jobapps
Content-Type: application/json
Authorization: Bearer idhere

{
  "user_id": "733683e8-7d0a-4b04-ae52-b8e6a6109f7c",
  "title": "Jr Full Stack Engineer",
  "date_applied": "05-25-2024",
  "application_status": "pending",
  "company_name": "Databricks"
}